site_name: Hocrox
site_description: Hocrox is an image preprocessing and augmentation library. It provides a Keras like simple interface to make preprocessing and augmentation pipelines.
site_author: Abhishek Chatterjee
copyright: Copyright 2021 Abhishek Chatterjee
repo_url: https://github.com/imdeepmind/hocrox
edit_uri: https://github.com/imdeepmind/hocrox/tree/main/docs/
plugins:
  - search
  - mkdocstrings
theme:
  name: material
  palette:
    - sheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - Home: "index.md"
  - Install: "install.md"
  - Get Started: "get-started.md"
  - Docs:
      - Layers: "docs/layers.md"
      - Models: "docs/models.md"
      - Utils: "docs/utils.md"
  - Blogs: "blogs.md"
  - Contributors: "contributors.md"
site_url: https://hocrox.imdeepmind.com/
docs_dir: docs
site_dir: site
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/imdeepmind
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/imdeepmind
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/imdeepmind/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/imdeepmind
