site_name: Hocrox - Image Preprocessing and Augmentation Library
site_description: Hocrox is an image preprocessing and augmentation library. It provides a Keras like simple interface to make preprocessing and augmentation pipelines.
site_author: Abhishek Chatterjee
copyright: Copyright 2021 Abhishek Chatterjee
repo_url: https://github.com/imdeepmind/hocrox
edit_uri: https://github.com/imdeepmind/hocrox/tree/main/docs/
plugins:
  - search
  - mkdocstrings
theme:
  name: material
nav:
  - Home: "index.md"
  - "install.md"
  - "get-started.md"
  - Docs:
      - Layers: "docs/layers.md"
      - Models: "docs/models.md"
      - Utils: "docs/utils.md"
  - "blogs.md"
  - "contributors.md"
site_url: https://hocrox.imdeepmind.com/
docs_dir: docs
site_dir: site
extra:
  version:
    provider: mike
